common_users:
  - name: sperkbird
    admin: true
    authorized_keys:
      - https://github.com/sperkbird.keys
  - name: wate
    admin: true
    authorized_keys:
      - https://github.com/wate.keys
  - name: nogajun
    admin: true
    authorized_keys:
      - https://github.com/nogajun.keys

dehydrated_domains:
  - name: "{{ inventory_hostname }}"
    domains: "{{ inventory_hostname }}"

nginx_vhosts:
  - name: default
    default: true
    server_name: "{{ inventory_hostname }}"
    upstream:
      name: backend
      content: |
        server unix:{{ redmine_home }}/tmp/redmine.sock;
    client_max_body_size: 0
    locations:
      - pattern: "/.well-known/acme-challenge/"
        match_type: "^~"
        content: |
          alias /var/lib/dehydrated/acme-challenges/;
      - pattern: /
        content: |
          proxy_pass http://backend;
          include proxy_params;
    # ssl:
    #   certificate: /var/lib/dehydrated/certs/{{ inventory_hostname }}/fullchain.pem
    #   certificate_key: /var/lib/dehydrated/certs/{{ inventory_hostname }}/privkey.pem
    #   trusted_certificate: /var/lib/dehydrated/certs/{{ inventory_hostname }}/chain.pem
    #   session_timeout: "1d"
    #   session_cache: "shared:SSL:10m"
    #   session_tickets: false
    #   # hsts: "max-age={{ 60 * 60 * 24 * (365 / 2) }}; includeSubDomains;"
    #   stapling: true
    #   stapling_verify: true

redmine_restore: true
redmine_restore_files_archive_file: "/tmp/redmine_files_archive.tar.gz"
redmine_restore_database_dump_file: "/tmp/redmine_database_dump.tar.gz"

redmine_db_cfg:
  production:
    adapter: mysql2
    database: "{{ lookup('env', 'REDMINE_DB_NAME') }}"
    host: "{{ lookup('env', 'REDMINE_DB_HOST') }}"
    username: "{{ lookup('env', 'REDMINE_DB_USER') }}"
    password: "{{ lookup('env', 'REDMINE_DB_PASSWORD') }}"
    encoding: utf8mb4
