common_users:
  - name: sperkbird
    admin: true
    password: "{{ lookup('csvfile', 'sperkbird', file='users.csv', delimiter=',') | password_hash('sha512') }}"
    authorized_keys:
      - key: https://github.com/sperkbird.keys
  - name: wate
    admin: true
    password: "{{ lookup('csvfile', 'wate', file='users.csv', delimiter=',') | password_hash('sha512')  }}"
    authorized_keys:
      - key: https://github.com/wate.keys
  - name: nogajun
    admin: true
    password: "{{ lookup('csvfile', 'nogajun', file='users.csv', delimiter=',') | password_hash('sha512')  }}"
    authorized_keys:
      - key: https://github.com/nogajun.keys

dehydrated_domains:
  - name: "{{ inventory_hostname }}"
    domains: "{{ inventory_hostname }}"

dehydrated_hook_deploy_cert: |
  systemctl restart nginx
dehydrated_hook_deploy_ocsp: |
  systemctl restart nginx

nginx_vhosts:
  - name: default
    default: true
    server_name: "{{ inventory_hostname }}"
    upstream:
      name: backend
      content: |
        server unix:{{ redmine_home }}/tmp/redmine.sock;
    client_max_body_size: 0
    locations:
      - pattern: "/.well-known/acme-challenge/"
        match_type: "^~"
        content: |
          alias /var/lib/dehydrated/acme-challenges/;
      - pattern: /
        content: |
          proxy_pass http://backend;
          include proxy_params;
    # ssl:
    #   certificate: /var/lib/dehydrated/certs/{{ inventory_hostname }}/fullchain.pem
    #   certificate_key: /var/lib/dehydrated/certs/{{ inventory_hostname }}/privkey.pem
    #   trusted_certificate: /var/lib/dehydrated/certs/{{ inventory_hostname }}/chain.pem
    #   session_timeout: "1d"
    #   session_cache: "shared:SSL:10m"
    #   session_tickets: false
    #   # hsts: "max-age={{ 60 * 60 * 24 * (365 / 2) }}; includeSubDomains;"
    #   stapling: true
    #   stapling_verify: true

redmine_cfg:
  default:
    email_delivery:
      delivery_method: :sendmail
    sudo_mode: true
    sudo_mode_timeout: 15

redmine_db_cfg:
  production:
    adapter: mysql2
    database: "{{ lookup('env', 'REDMINE_DB_NAME') }}"
    host: "{{ lookup('env', 'REDMINE_DB_HOST') }}"
    username: "{{ lookup('env', 'REDMINE_DB_USER') }}"
    password: "{{ lookup('env', 'REDMINE_DB_PASSWORD') }}"
    encoding: utf8mb4

redmine_themes:
  - name: PurpleMine2
    repo: https://github.com/mrliptontea/PurpleMine2.git
  - name: farend_fancy
    repo: https://github.com/farend/redmine_theme_farend_fancy.git
  - name: farend_basic
    repo: https://github.com/farend/redmine_theme_farend_basic.git

redmine_plugins:
  - name: additionals
    repo: https://github.com/AlphaNodes/additionals.git
    version: "3.0.5.2"
  - name: sudo
    repo: https://github.com/AlphaNodes/redmine_sudo.git
    version: stable
  - name: view_customize
    repo: https://github.com/onozaty/redmine-view-customize.git
    directory: view_customize
  - name: message_customize
    repo: https://github.com/ishikawa999/redmine_message_customize.git
  - name: issue_templates
    repo: https://github.com/agileware-jp/redmine_issue_templates.git
  - name: slack
    repo: https://github.com/cat-in-136/redmine-slack.git
    version: evolved
  - name: drawio
    repo: https://github.com/mikitex70/redmine_drawio.git
  - name: redmica_ui_extension
    repo: https://github.com/redmica/redmica_ui_extension.git
    directory: redmica_ui_extension
  - name: dmsf
    repo: https://github.com/danmunn/redmine_dmsf.git
    version: "v3.0.2"
