- name: Deploy Redmine
  hosts: redmine
  become: true
  pre_tasks:
    - name: rcloneのインストール
      ansible.builtin.apt:
        name: rclone
    - name: rcloneの設定ファイル保存用ディレクトリの作成
      ansible.builtin.file:
        path: ~/.config/rclone
        state: directory
        mode: "0755"
    - name: rcloneの設定を生成
      community.general.ini_file:
        path: ~/.config/rclone/rclone.conf
        section: sakura_cloud
        option: "{{ item.name }}"
        value: "{{ item.value }}"
        mode: "0600"
        create: true
      loop_control:
        label: "{{ item.name }}"
      loop:
        - name: type
          value: s3
        - name: provider
          value: Other
        - name: access_key_id
          value: "{{ lookup('env', 'OBJECT_STORAGE_ACCESS_KEY_ID') }}"
        - name: secret_access_key
          value: "{{ lookup('env', 'OBJECT_STORAGE_SECRET_ACCESS_KEY') }}"
        - name: region
          value: "{{ lookup('env', 'OBJECT_STORAGE_REGION') }}"
        - name: endpoint
          value: "{{ lookup('env', 'OBJECT_STORAGE_ENDPOINT') }}"
        - name: acl
          value: private
  roles:
    - role: common
      tags: role_common
    - role: mackerel_agent
      tags: role_mackerel_agent
    - role: nginx
      tags: role_nginx
    - role: dehydrated
      tags: role_dehydrated
    - role: redmine
      tags: role_redmine
  tasks: []
