- src: https://github.com/wate/ansible-role-common
  version: master
  name: common
- src: https://github.com/wate/ansible-role-nginx.git
  version: master
  name: nginx
- src: https://github.com/wate/ansible-role-dehydrated.git
  version: master
  name: dehydrated
- src: https://github.com/wate/ansible-role-redmine.git
  version: master
  name: redmine
- src: https://github.com/wate/ansible-role-mackerel_agent.git
  version: master
  name: mackerel_agent
